export const site = {
  name: "Žilić Consult",
  origin: process.env.SITE_ORIGIN || "https://www.zilic-consult.com",
  language: "en",
  email: "tonci.zilic18@gmail.com",
  linkedin: "https://www.linkedin.com/in/tonci4",
  author: "Tonći Žilić",
  image: "/assets/img/tonci-zilic.jpg",
  lastModified: "2026-08-31",
  analytics: {
    measurementId: "G-29C2MGDK96",
    siteVerification: "cWyoBFBfdtnz89riM6l5uIQLj1scNgQo-r-FRRWMws0",
  },
};

const servicePages = [
  {
    path: "/services/product-mobility-strategy/",
    family: "service",
    title: "Product & Mobility Strategy Consultant | Žilić Consult",
    description: "Independent product and mobility strategy consulting for B2B technology, automotive and mobility teams facing complex product decisions and launches.",
    eyebrow: "Product and mobility strategy",
    h1: "Product strategy for complex mobility and technology products.",
    answer: "Žilić Consult helps founders and leadership teams turn a complex product opportunity into a focused proposition, defensible roadmap and executable product plan.",
    intro: [
      "This engagement is for products where hardware, software, operations and commercial constraints must work together. It connects customer value, technical reality and the business case before teams commit significant time or capital.",
      "The work is led directly by Tonći Žilić and shaped by experience across connected vehicles, automotive-grade development, robotaxi product definition and early-stage company building.",
    ],
    situations: [
      "A product vision exists, but priorities and product boundaries are unclear.",
      "Engineering, commercial and operational teams are optimizing for different outcomes.",
      "A mobility service needs a coherent rider, operator and fleet proposition.",
      "Leadership needs an independent challenge before approving a roadmap or investment.",
    ],
    deliverables: [
      "Product proposition and target-customer definition",
      "Product principles, requirements and decision criteria",
      "Roadmap options with dependencies, risks and trade-offs",
      "Service blueprint across customer, technology and operations",
      "Executive recommendation and practical next-step plan",
    ],
    process: "Work usually begins with existing evidence, stakeholder interviews and the decisions that cannot be postponed. The output is a small set of choices and an operating plan, not a strategy deck detached from delivery.",
    related: ["/industries/automotive/", "/industries/autonomous-mobility/", "/for/product-leaders/", "/how-i-work/"],
    faqs: [
      ["Is this only for automotive companies?", "No. The method fits complex B2B and technology products, especially when software, hardware, service operations or regulated partners are interdependent."],
      ["Can you work with an existing product team?", "Yes. The role can be an independent strategy lead, a focused extension of the product function or interim product leadership for a defined period."],
    ],
  },
  {
    path: "/services/market-readiness/",
    family: "service",
    title: "Market Readiness Consultant for B2B Products | Žilić Consult",
    description: "Market readiness consulting for B2B technology and mobility companies: validation, segmentation, positioning, buying process and launch decision support.",
    eyebrow: "Market readiness",
    h1: "Know what must be true before you take a product to market.",
    answer: "Žilić Consult tests whether a B2B product is ready for market by connecting customer evidence, positioning, buying dynamics, product gaps and commercial assumptions.",
    intro: [
      "Market readiness is not a launch checklist. It is a decision about whether a specific customer has a strong enough problem, whether the offer is credible and whether the organization can sell and deliver it.",
      "The engagement turns scattered research, founder conviction and early customer conversations into explicit evidence, open questions and a go, change or pause recommendation.",
    ],
    situations: [
      "The team is preparing a first commercial launch or enterprise pilot.",
      "Customer interest is positive, but conversion and urgency remain uncertain.",
      "The product has expanded faster than its positioning and target segment.",
      "Leadership needs a clear readiness view before funding the next phase.",
    ],
    deliverables: [
      "Target segment and ideal-customer profile",
      "Problem, alternative and willingness-to-change evidence",
      "Positioning and value proposition",
      "Buying committee and sales-friction map",
      "Readiness scorecard with evidence gaps and actions",
    ],
    process: "The assessment separates observed customer evidence, internal assumptions and external market facts. Recommendations show what is known, what is inferred and what still needs validation.",
    related: ["/services/market-entry-launch/", "/services/b2b-enterprise-pricing/", "/for/founders/", "/methodology/"],
    faqs: [
      ["Can this be done before the product is built?", "Yes. Early readiness work can test the problem, buyer, proposition and commercial model before a full build, while clearly labelling what remains unproven."],
      ["Does the engagement include customer interviews?", "It can. The scope may use existing evidence, new interviews or both, depending on the decision, access and timeline."],
    ],
  },
  {
    path: "/services/market-entry-launch/",
    family: "service",
    title: "Market Entry & Launch Consultant | Žilić Consult",
    description: "Market entry and launch consulting for technology, automotive and mobility companies expanding into new countries, partnerships or operating models.",
    eyebrow: "Market entry and launch",
    h1: "Enter the right market with an executable launch plan.",
    answer: "Žilić Consult helps technology and mobility companies evaluate markets, choose an entry model and coordinate the product, partner and operational work required for launch.",
    intro: [
      "A market can look attractive in a presentation and still be wrong for the product, economics or operating model. Entry planning must connect demand, regulation, channels, partnerships, localization, service delivery and launch sequencing.",
      "The result is a decision-ready comparison and a practical launch architecture with owners, dependencies and risk controls.",
    ],
    situations: [
      "A company is choosing between several countries or cities.",
      "A product requires local operating, distribution or public-sector partners.",
      "The commercial team has a target date but no integrated launch plan.",
      "Leadership needs to understand the cost and complexity behind market potential.",
    ],
    deliverables: [
      "Market selection criteria and comparative assessment",
      "Entry-mode and partner strategy",
      "Localization, regulatory and operational requirements",
      "Integrated launch plan and critical path",
      "Risk register, decision gates and executive recommendation",
    ],
    process: "The work uses authoritative external sources, company data and stakeholder input. Every important market claim is tied to its source and date; estimates and assumptions are explicitly marked.",
    related: ["/services/market-readiness/", "/industries/autonomous-mobility/", "/for/coos/", "/sources/"],
    faqs: [
      ["Do you provide legal or regulatory advice?", "No. Regulatory issues are identified and coordinated, but qualified local counsel or specialists should confirm legal interpretations."],
      ["Can you support launch execution?", "Yes. Support can continue through partner selection, launch governance, readiness reviews and a defined interim leadership mandate."],
    ],
  },
  {
    path: "/services/b2b-enterprise-pricing/",
    family: "service",
    title: "B2B Enterprise Pricing Consultant | Žilić Consult",
    description: "B2B enterprise pricing consulting for technology and mobility offers: value metrics, packaging, commercial models, deal logic and pricing governance.",
    eyebrow: "B2B enterprise pricing",
    h1: "Price complex B2B products around value, not internal habit.",
    answer: "Žilić Consult helps B2B teams define pricing, packaging and commercial rules that customers can understand, sales teams can use and the business can deliver profitably.",
    intro: [
      "Enterprise pricing is a product and operating decision, not only a number. The value metric, package boundaries, implementation effort, contract structure and approval process all shape willingness to buy and margin.",
      "The engagement creates a coherent model from customer value and deal evidence, while preserving room to learn where data is still limited.",
    ],
    situations: [
      "Every enterprise proposal is custom and difficult to compare.",
      "Pricing was inherited from an early pilot or a competitor.",
      "The offer combines software, hardware, integration and ongoing service.",
      "Discounting and approval decisions depend on individual judgement.",
    ],
    deliverables: [
      "Customer-value and willingness-to-pay hypotheses",
      "Value metric, package structure and price architecture",
      "Commercial model for recurring, usage and service components",
      "Deal guardrails, discount logic and approval governance",
      "Testing plan and sales enablement material",
    ],
    process: "Pricing work combines customer and deal evidence with cost-to-serve, competitive alternatives and strategic positioning. Where evidence is incomplete, outputs are framed as testable decisions rather than false precision.",
    related: ["/industries/technology-b2b/", "/for/ceos/", "/for/product-leaders/", "/services/market-readiness/"],
    faqs: [
      ["Is this suitable for an early-stage startup?", "Yes, if there is a defined offer and enough customer or pilot evidence to make useful choices. The model can be designed to learn without locking the company into premature complexity."],
      ["Do you benchmark competitor prices?", "When reliable public or client-provided evidence exists. Competitor prices are context, not a substitute for understanding customer value and the economics of delivery."],
    ],
  },
  {
    path: "/services/startup-fundraising/",
    family: "service",
    title: "Pre-Seed & Seed Fundraising Advisor | Žilić Consult",
    description: "Fundraising strategy and investor-readiness support for pre-seed and seed founders, including narrative, pitch deck, data room and process planning.",
    eyebrow: "Pre-seed and seed fundraising",
    h1: "Build an investor case that survives the second conversation.",
    answer: "Žilić Consult helps pre-seed and seed founders turn product, market and operating evidence into a clear investor narrative, credible materials and a disciplined fundraising process.",
    intro: [
      "A pitch deck is only one part of fundraising readiness. Investors also test the consistency between the market claim, customer evidence, product plan, use of funds, milestones and team capability.",
      "Support focuses on the quality of the case and the founder's decision process. It does not promise introductions, investment or a particular valuation.",
    ],
    situations: [
      "The company is raising its first institutional round.",
      "The story is technically strong but commercially difficult to follow.",
      "The team needs to align milestones and use of funds with the round.",
      "Existing materials do not hold together across deck, model and data room.",
    ],
    deliverables: [
      "Fundraising thesis, target investor profile and process plan",
      "Investor narrative and pitch-deck structure",
      "Evidence map for market, product and traction claims",
      "Data-room checklist and diligence readiness",
      "Q&A preparation, feedback synthesis and iteration plan",
    ],
    process: "The process starts with the investment case, not slide design. Claims are challenged against available evidence, and unsupported assumptions are either validated, qualified or removed.",
    related: ["/for/founders/", "/services/market-readiness/", "/services/product-mobility-strategy/", "/methodology/"],
    faqs: [
      ["Do you introduce founders to investors?", "Introductions are not the core service and are never guaranteed. The engagement is designed to improve readiness, targeting, materials and process quality."],
      ["Do you write the entire pitch deck?", "The narrative and content can be developed together, but founders remain responsible for the claims and should be able to defend every part of the case."],
    ],
  },
  {
    path: "/services/robotaxi-autonomous-mobility/",
    family: "service",
    title: "Robotaxi & Autonomous Mobility Consultant | Žilić Consult",
    description: "Robotaxi and autonomous mobility consulting across product definition, rider experience, fleet operations, market launch and programme readiness.",
    eyebrow: "Robotaxi and autonomous mobility",
    h1: "Turn autonomous technology into a service people can actually use.",
    answer: "Žilić Consult supports robotaxi and autonomous mobility programmes where vehicle technology, rider experience, fleet operations and city launch must become one coherent product.",
    intro: [
      "A robotaxi service is more than an autonomous vehicle. Booking, pickup, access, in-cabin experience, remote assistance, cleaning, charging, incident handling and local operations all affect whether the service works.",
      "The work draws on direct robotaxi product and programme experience while remaining independent of any vehicle, autonomy stack or operating platform vendor.",
    ],
    situations: [
      "A programme needs an end-to-end customer and service definition.",
      "Vehicle, app, fleet and operations teams have disconnected requirements.",
      "A city launch requires integrated readiness and decision gates.",
      "Leadership needs an independent product or programme review.",
    ],
    deliverables: [
      "Service proposition and target use cases",
      "End-to-end rider journey and service blueprint",
      "Cross-system product requirements and ownership map",
      "Fleet, support and operational readiness model",
      "Launch gates, scenario reviews and programme risks",
    ],
    process: "Work is grounded in the intended operating domain, customer journey and service responsibilities. Technical capability is treated as an input to the product, not evidence that the complete service is ready.",
    related: ["/industries/autonomous-mobility/", "/industries/automotive/", "/services/market-entry-launch/", "/for/coos/"],
    faqs: [
      ["Do you develop autonomous-driving software?", "No. The focus is product, programme, rider experience, service operations and launch integration around the autonomous-driving system."],
      ["Can you support a specific city launch?", "Yes, subject to scope and access. Local regulatory and legal conclusions must be confirmed by qualified local authorities or advisers."],
    ],
  },
  {
    path: "/services/interim-product-leadership/",
    family: "service",
    title: "Interim Product Leader for B2B & Mobility | Žilić Consult",
    description: "Interim senior product leadership for B2B technology, automotive and mobility teams during launches, transitions, transformations or critical programmes.",
    eyebrow: "Interim product leadership",
    h1: "Senior product leadership for the period when it matters most.",
    answer: "Žilić Consult provides hands-on interim product or programme leadership for a defined transition, launch or transformation, with clear authority, outcomes and handover.",
    intro: [
      "An interim mandate is appropriate when the organization needs senior ownership now but the requirement is time-bound, still evolving or tied to a specific programme.",
      "The role combines decision-making, team alignment and delivery governance. It is not a passive advisory retainer presented as operating leadership.",
    ],
    situations: [
      "A product leader has left during a critical delivery period.",
      "A launch or transformation needs senior cross-functional ownership.",
      "The company is defining the permanent role while work must continue.",
      "A founder needs temporary product leadership and a stronger operating cadence.",
    ],
    deliverables: [
      "Mandate, decision rights and success measures",
      "Product priorities and delivery operating cadence",
      "Cross-functional issue and dependency management",
      "Leadership reporting and decision preparation",
      "Documented handover to the permanent owner",
    ],
    process: "Each mandate starts with explicit outcomes, authority, time commitment and conflicts. Progress is measured against operating results and decisions, with a planned exit rather than open-ended dependency.",
    related: ["/for/product-leaders/", "/for/ceos/", "/for/coos/", "/how-i-work/"],
    faqs: [
      ["Is this a full-time role?", "It can be structured as a fractional or higher-intensity mandate depending on the need. Availability, conflicts and decision rights are agreed before work starts."],
      ["Do you manage the existing team?", "Yes when the mandate requires it and the reporting relationship is explicit. Other engagements may focus on a programme or decision stream without line management."],
    ],
  },
  {
    path: "/services/executive-advisory-workshops/",
    family: "service",
    title: "Executive Advisory & Strategy Workshops | Žilić Consult",
    description: "Independent executive advisory and focused strategy workshops for CEOs, COOs and product leaders making complex product, market and operating decisions.",
    eyebrow: "Executive advisory and workshops",
    h1: "Independent decision support for high-consequence choices.",
    answer: "Žilić Consult gives CEOs, COOs and product leaders a structured independent view on product, market, commercial and operating decisions.",
    intro: [
      "Leadership teams often have enough information but lack a neutral process for resolving assumptions, trade-offs and ownership. A focused advisory engagement creates the evidence and decision structure without adding an agency layer.",
      "Formats range from a single decision workshop to a monthly retainer, vendor review or short strategy sprint.",
    ],
    situations: [
      "A strategic decision is stuck between functions or stakeholders.",
      "Leadership wants an independent challenge to an internal proposal.",
      "A partner, vendor or investment option needs structured evaluation.",
      "A management team needs a facilitated working session with concrete outputs.",
    ],
    deliverables: [
      "Decision framing and pre-read",
      "Evidence, assumptions and option comparison",
      "Facilitated executive workshop",
      "Recommendation, decisions and action ownership",
      "Follow-up advisory cadence where useful",
    ],
    process: "The scope is anchored to decisions and outcomes. Advice distinguishes verified facts, professional judgement and open assumptions so leaders can see exactly what supports the recommendation.",
    related: ["/for/ceos/", "/for/coos/", "/for/product-leaders/", "/methodology/"],
    faqs: [
      ["Can you facilitate an off-site?", "Yes, when the session has a defined business decision or working outcome. General team-building events are outside the core offer."],
      ["Is advice confidential?", "Engagements are handled under agreed confidentiality terms and screened for conflicts before sensitive information is shared."],
    ],
  },
];

const audiencePages = [
  {
    path: "/for/ceos/",
    family: "audience",
    title: "B2B CEO Advisor for Product, Market & Growth | Žilić Consult",
    description: "Independent advisor to B2B CEOs on product strategy, market entry, enterprise pricing, fundraising, operating choices and executive decisions.",
    eyebrow: "For B2B CEOs",
    h1: "A direct, independent advisor for product, market and growth decisions.",
    answer: "Žilić Consult works directly with B2B CEOs who need senior product and commercial judgement on a defined decision, launch, financing process or transition.",
    intro: [
      "The value is an experienced outside view without a large consulting team. Work can challenge a strategy, integrate competing functional perspectives or take temporary ownership of a critical stream.",
      "The engagement is particularly relevant to technology, automotive and mobility businesses where product choices have operational and capital consequences.",
    ],
    situations: [
      "You need to decide where the product should focus and what to stop.",
      "A new market, price model or launch needs independent scrutiny.",
      "The investor story and operating plan do not yet reinforce each other.",
      "A critical programme needs temporary senior ownership.",
    ],
    deliverables: [
      "Clear decision frame and evidence requirements",
      "Independent option and risk assessment",
      "Executive recommendation with trade-offs",
      "Aligned action plan and ownership",
      "Ongoing advisory or interim support where needed",
    ],
    process: "Engagements are deliberately small, direct and confidential. Scope, conflicts, decision rights and expected outcomes are agreed before access to sensitive information.",
    related: ["/services/executive-advisory-workshops/", "/services/b2b-enterprise-pricing/", "/services/interim-product-leadership/", "/industries/technology-b2b/"],
    faqs: [
      ["Do you work alongside an existing executive team?", "Yes. The work is designed to strengthen decisions and execution with the existing team, not bypass functional owners."],
      ["Is this a board-advisor role?", "It can support board preparation or a defined advisory mandate, but formal fiduciary or director responsibilities require a separate agreement."],
    ],
  },
  {
    path: "/for/coos/",
    family: "audience",
    title: "COO Advisor for Launch, Operations & Scale | Žilić Consult",
    description: "Independent COO advisory for technology and mobility leaders managing launch readiness, operating models, cross-functional programmes and scale.",
    eyebrow: "For COOs",
    h1: "Connect the strategy to the operating system required to deliver it.",
    answer: "Žilić Consult helps COOs turn product and market commitments into launch plans, operating responsibilities, readiness gates and cross-functional execution.",
    intro: [
      "Complex products fail at the seams between functions. The work makes dependencies visible across product, technology, commercial, partner and service operations before they become launch problems.",
      "Support can be a readiness review, operating-model sprint, programme reset or interim leadership mandate.",
    ],
    situations: [
      "The launch date exists, but readiness criteria and ownership do not.",
      "A new market depends on local partners and operational setup.",
      "Product decisions are creating hidden service or support costs.",
      "A cross-functional programme has activity but weak decision governance.",
    ],
    deliverables: [
      "Operating model and responsibility map",
      "Integrated plan, dependencies and critical path",
      "Readiness criteria and decision gates",
      "Risk, issue and escalation structure",
      "Leadership reporting and launch governance",
    ],
    process: "The work starts from the promised customer outcome and traces what every function and partner must make true. Unknowns and assumptions remain visible until resolved.",
    related: ["/services/market-entry-launch/", "/services/robotaxi-autonomous-mobility/", "/services/interim-product-leadership/", "/how-i-work/"],
    faqs: [
      ["Can you review an existing operating model?", "Yes. The review can focus on responsibilities, bottlenecks, service economics, launch readiness or a specific transformation."],
      ["Do you provide project management?", "Programme leadership can be included, but the core value is decision and operating integration rather than administrative project tracking."],
    ],
  },
  {
    path: "/for/product-leaders/",
    family: "audience",
    title: "Product Leadership Advisor for Complex B2B Products",
    description: "Product leadership advisory for complex B2B, automotive and mobility products: strategy, roadmaps, requirements, operating alignment and launches.",
    eyebrow: "For product leaders",
    h1: "Strengthen the product decisions that cross organizational boundaries.",
    answer: "Žilić Consult supports product leaders with strategy, roadmap, requirements and cross-functional decisions for products that combine technology, operations and commercial constraints.",
    intro: [
      "The engagement adds senior capacity where product work extends beyond a single software team: connected services, physical products, enterprise implementation, partner ecosystems and mobility operations.",
      "It can provide an independent review, facilitate alignment or temporarily own a defined product area.",
    ],
    situations: [
      "The roadmap contains output but lacks strategic choices.",
      "Requirements are fragmented across systems and operating teams.",
      "Stakeholders disagree on target customer, scope or launch threshold.",
      "The function needs interim senior support during a transition.",
    ],
    deliverables: [
      "Product strategy and decision principles",
      "Outcome-based roadmap and dependency view",
      "Cross-system requirement and ownership structure",
      "Stakeholder decision and governance cadence",
      "Launch criteria and learning plan",
    ],
    process: "Work is done with the existing product organization and its source material. The objective is stronger internal capability and decisions, with clear handover of every framework used.",
    related: ["/services/product-mobility-strategy/", "/services/interim-product-leadership/", "/services/b2b-enterprise-pricing/", "/industries/automotive/"],
    faqs: [
      ["Can you coach product managers?", "Yes, when coaching is tied to live product decisions and ways of working. Generic training can be delivered as a focused workshop."],
      ["Can you own requirements across hardware and software?", "Yes for product and programme integration within the agreed mandate, working with the responsible engineering and specialist leads."],
    ],
  },
  {
    path: "/for/founders/",
    family: "audience",
    title: "Startup Advisor for B2B & Mobility Founders | Žilić Consult",
    description: "Practical startup advisory for B2B technology and mobility founders working through product focus, market readiness, pricing and seed fundraising.",
    eyebrow: "For founders",
    h1: "Make the next company-defining decision with better evidence.",
    answer: "Žilić Consult helps B2B and mobility founders sharpen product focus, validate the market, design enterprise pricing and prepare a credible pre-seed or seed raise.",
    intro: [
      "Early-stage teams cannot research every option or build every opportunity. The work creates enough evidence to choose a customer, proposition, commercial model and milestone sequence without pretending uncertainty has disappeared.",
      "Support is founder-direct and scoped around a concrete decision or financing milestone.",
    ],
    situations: [
      "The company has several promising customer directions but no focus.",
      "Pilot interest is not translating into a repeatable offer.",
      "The enterprise price and package are still improvised deal by deal.",
      "The fundraising story is ahead of the evidence or operating plan.",
    ],
    deliverables: [
      "Customer and problem focus",
      "Market-readiness and evidence plan",
      "Offer, package and pricing architecture",
      "Fundraising narrative and milestone logic",
      "Prioritized operating plan for the next stage",
    ],
    process: "Advice separates observed evidence, founder judgement and open assumptions. The goal is a decision that can be tested quickly, not certainty manufactured from limited startup data.",
    related: ["/services/market-readiness/", "/services/startup-fundraising/", "/services/b2b-enterprise-pricing/", "/industries/technology-b2b/"],
    faqs: [
      ["What startup stages do you support?", "The strongest fit is pre-seed through seed, plus early growth decisions where product, enterprise sales and operating model are still being shaped."],
      ["Do you take equity?", "Engagement terms depend on scope and are agreed directly. No standard equity-for-advice offer is presented on this site."],
    ],
  },
];

const industryPages = [
  {
    path: "/industries/automotive/",
    family: "industry",
    title: "Automotive Product & Strategy Consultant | Žilić Consult",
    description: "Automotive consulting across product strategy, connected vehicles, automotive-grade programmes, market readiness and launch planning.",
    eyebrow: "Automotive consulting",
    h1: "Automotive product strategy grounded in delivery reality.",
    answer: "Žilić Consult supports automotive companies and suppliers with product strategy, connected services, programme decisions and market launches where technical and commercial choices must stay aligned.",
    intro: [
      "Automotive products operate within long development cycles, quality requirements, supplier dependencies and high capital commitments. Digital and connected services add a faster customer and software layer to that environment.",
      "The perspective comes from direct product and programme roles at Rimac Automobili and Rimac Technology, including connected vehicle services and automotive-grade development.",
    ],
    situations: [
      "A digital or connected proposition must fit the vehicle programme.",
      "Product and programme requirements need stronger commercial context.",
      "A partner or vendor decision has long-term architecture implications.",
      "A new product or market launch needs cross-functional readiness.",
    ],
    deliverables: [
      "Product proposition and use-case priorities",
      "Customer, vehicle and service requirement alignment",
      "Roadmap and programme decision support",
      "Partner and vendor evaluation criteria",
      "Market and launch readiness plan",
    ],
    process: "Advice is independent and based on the engagement evidence. Previous employers are professional background, not consulting clients or endorsements.",
    related: ["/services/product-mobility-strategy/", "/services/market-entry-launch/", "/industries/autonomous-mobility/", "/about/"],
    faqs: [
      ["Do you work with OEMs and suppliers?", "Yes, where the mandate fits product, connected services, programme, market or operating expertise and passes conflict checks."],
      ["Are Rimac and Verne consulting clients?", "No. They are part of Tonći Žilić's professional background. The site states this distinction wherever that experience is referenced."],
    ],
  },
  {
    path: "/industries/autonomous-mobility/",
    family: "industry",
    title: "Autonomous Mobility & Robotaxi Advisor | Žilić Consult",
    description: "Autonomous mobility and robotaxi advisory for product, rider experience, fleet operations, service readiness, partnerships and city launch.",
    eyebrow: "Autonomous mobility",
    h1: "Design the service around the autonomous system.",
    answer: "Žilić Consult helps autonomous mobility teams connect vehicle capability to the rider journey, fleet operation, support model, market entry and launch programme.",
    intro: [
      "Autonomous driving capability is essential, but it does not define the complete customer service. The operating design around pickup, remote assistance, vehicle recovery, charging, cleaning and incident response is also part of the product.",
      "Support focuses on the interfaces between these systems and teams, where programme risk and customer friction usually accumulate.",
    ],
    situations: [
      "The programme needs a complete service definition beyond the vehicle.",
      "Customer, fleet and operational requirements lack a shared owner.",
      "A city or campus launch needs clear readiness gates.",
      "A leadership team needs an independent programme assessment.",
    ],
    deliverables: [
      "Rider and operator service blueprint",
      "Use cases and operating-domain assumptions",
      "Cross-system requirements and failure scenarios",
      "Fleet and support operating model",
      "Market launch plan and readiness governance",
    ],
    process: "The work distinguishes product requirements, engineering evidence, operational assumptions and external regulatory confirmation. None is presented as interchangeable with another.",
    related: ["/services/robotaxi-autonomous-mobility/", "/services/market-entry-launch/", "/for/coos/", "/sources/"],
    faqs: [
      ["Is the advice tied to a specific autonomy stack?", "No. The work is vendor-independent and focuses on product, programme, service operations and launch integration."],
      ["Can you certify safety or regulatory compliance?", "No. Safety cases, certification and legal compliance require the responsible qualified organizations and authorities."],
    ],
  },
  {
    path: "/industries/technology-b2b/",
    family: "industry",
    title: "B2B Technology Product & Growth Consultant | Žilić Consult",
    description: "B2B technology consulting across product focus, enterprise pricing, market readiness, go-to-market decisions and interim product leadership.",
    eyebrow: "B2B technology",
    h1: "Product and growth decisions for complex B2B technology.",
    answer: "Žilić Consult helps B2B technology teams focus the product, define the enterprise offer, test market readiness and create a practical path to launch and growth.",
    intro: [
      "Complex B2B products are shaped by more than end-user needs. Buying committees, integrations, implementation effort, operating change, risk and procurement all influence the product and commercial model.",
      "The work connects those realities so product, pricing and go-to-market choices reinforce one another.",
    ],
    situations: [
      "The product serves many possible customer types and needs focus.",
      "Enterprise deals require too much custom scope and pricing.",
      "A new offer is moving toward launch without sufficient market evidence.",
      "The company needs senior product capacity for a defined transition.",
    ],
    deliverables: [
      "Ideal-customer and buying-committee definition",
      "Product proposition and roadmap choices",
      "Enterprise package and pricing architecture",
      "Market-readiness and launch plan",
      "Product operating model or interim leadership",
    ],
    process: "Recommendations use available customer, pipeline, product and delivery evidence. Market claims and assumptions are labelled so the team knows what to validate next.",
    related: ["/services/market-readiness/", "/services/b2b-enterprise-pricing/", "/for/ceos/", "/for/founders/"],
    faqs: [
      ["Is this only for SaaS companies?", "No. The strongest fit includes B2B products that combine software with hardware, implementation, data, services or complex operational workflows."],
      ["Can you work with sales and product together?", "Yes. Many engagements are designed specifically to resolve the interface between customer evidence, product choices and enterprise selling."],
    ],
  },
];

const institutionalPages = [
  {
    path: "/about/",
    family: "institutional",
    title: "About Tonći Žilić | Product & Mobility Consultant",
    description: "Background of Tonći Žilić, an independent product and mobility consultant with experience at Rimac, Verne and as a technology company founder.",
    eyebrow: "About",
    h1: "Tonći Žilić: product, programme and company-building experience.",
    answer: "Tonći Žilić is an independent consultant working with founders and executives on product, market, commercial and operating decisions in technology, automotive and mobility.",
    intro: [
      "His background spans connected vehicle services, automotive-grade product and programme work, robotaxi product definition and operations, and co-founding technology companies.",
      "He joined Rimac Automobili among its first hundred employees, later held roles at Rimac Technology and Verne, and has co-founded SheepAI and Serenity. These organizations are professional experience unless explicitly identified as a consulting client.",
    ],
    situations: [
      "Product strategy across hardware, software and service operations",
      "Automotive and connected vehicle product programmes",
      "Robotaxi rider experience and launch readiness",
      "Early-stage product, commercial and fundraising decisions",
    ],
    deliverables: [
      "Direct senior involvement throughout the engagement",
      "Engineering literacy connected to commercial judgement",
      "Clear distinction between evidence, inference and recommendation",
      "Small, confidential scopes without an agency layer",
      "Practical outputs designed for decisions and delivery",
    ],
    process: "Availability and conflicts are checked before an engagement. Claims on this site describe professional background and service capability; they do not imply endorsement by previous employers.",
    related: ["/how-i-work/", "/methodology/", "/industries/automotive/", "/industries/autonomous-mobility/"],
    faqs: [
      ["Where is Žilić Consult based?", "The consultancy works internationally and confirms location, travel and contracting details directly for each engagement."],
      ["How can I verify the professional background?", "The LinkedIn profile linked on this site provides the current public career record. Engagement-specific references can be discussed where confidentiality permits."],
    ],
  },
  {
    path: "/how-i-work/",
    family: "institutional",
    title: "How Žilić Consult Works | Engagement Models",
    description: "How consulting engagements are scoped, evidenced and delivered: fixed projects, strategy sprints, advisory retainers, workshops and interim leadership.",
    eyebrow: "How I work",
    h1: "Flexible engagement models with explicit decisions and outcomes.",
    answer: "Every Žilić Consult engagement starts with a defined decision, outcome, scope and evidence base, then uses the lightest format capable of producing a useful result.",
    intro: [
      "Common formats include a fixed-scope strategy project, a fundraising or pricing sprint, a facilitated workshop, a monthly advisory retainer and an interim leadership mandate.",
      "The work is led directly by Tonći Žilić. Scope, time commitment, decision rights, confidentiality and conflicts are agreed before substantive work begins.",
    ],
    situations: [
      "Fixed-scope project for a strategy, market or launch decision",
      "Short sprint for pricing, readiness or fundraising materials",
      "Executive workshop with preparation and documented actions",
      "Interim mandate with operating ownership and planned handover",
    ],
    deliverables: [
      "Written scope, questions, outputs and exclusions",
      "Source and evidence review",
      "Working sessions with responsible stakeholders",
      "Decision-ready recommendation and action plan",
      "Handover, limitations and unresolved questions",
    ],
    process: "A typical sequence is diagnose, frame, gather evidence, develop options, decide and hand over. The exact sequence changes with the mandate, but facts, assumptions and recommendations remain visibly separated.",
    related: ["/methodology/", "/sources/", "/services/", "/for/"],
    faqs: [
      ["How long does an engagement take?", "A focused sprint may take days or weeks; strategy and interim mandates may run longer. Timing depends on the decision, access and depth required."],
      ["Do you work with competing companies?", "Potential conflicts are reviewed before engagement. Confidentiality and any sector or account restrictions are agreed in writing."],
    ],
  },
  {
    path: "/methodology/",
    family: "trust",
    title: "Consulting Methodology & Evidence Standards | Žilić Consult",
    description: "How Žilić Consult separates sourced facts, client evidence, analysis, assumptions and recommendations in product, market and operating work.",
    eyebrow: "Methodology and reliability",
    h1: "Decisions are stronger when evidence and judgement stay distinct.",
    answer: "Žilić Consult labels the basis of important conclusions: verified external fact, client-provided evidence, direct observation, analysis, assumption or recommendation.",
    intro: [
      "Consulting work often combines incomplete information from different dates and sources. Treating every input as equally reliable creates false confidence. The methodology makes provenance, freshness, limitations and ownership visible.",
      "The level of evidence is proportional to the decision. A rapid workshop and an investment-grade market assessment should not pretend to provide the same depth.",
    ],
    situations: [
      "Verified fact: supported by a named authoritative source and retrieval date",
      "Client evidence: supplied by the client and identified as such",
      "Observation: directly seen in research, product use or stakeholder work",
      "Analysis or estimate: derived from stated inputs and method",
      "Recommendation: professional judgement based on the available evidence",
    ],
    deliverables: [
      "Source register for material external claims",
      "Evidence and assumption log",
      "Observation and retrieval dates where freshness matters",
      "Confidence and limitation notes",
      "Clear ownership for unresolved validation",
    ],
    process: "No method eliminates uncertainty. The purpose is to keep uncertainty legible, make claims auditable and prevent an estimate or recommendation from being mistaken for official confirmation.",
    related: ["/sources/", "/how-i-work/", "/about/", "/services/executive-advisory-workshops/"],
    faqs: [
      ["Does every recommendation require public data?", "No. Client evidence, interviews and professional judgement may be more relevant. The basis and limitations should still be clear."],
      ["Are website pages updated automatically?", "No. Service and background pages are editorial content. Sitemap dates change only when the underlying page content changes materially."],
    ],
  },
  {
    path: "/sources/",
    family: "trust",
    title: "Sources, Provenance & Claim Limitations | Žilić Consult",
    description: "Source policy for Žilić Consult: authoritative external data, client-provided evidence, professional background claims, retrieval dates and limitations.",
    eyebrow: "Sources and provenance",
    h1: "How sources and professional claims are handled.",
    answer: "Žilić Consult prefers primary and authoritative sources, records when time-sensitive information was observed or retrieved, and states when a conclusion is an estimate or professional judgement.",
    intro: [
      "Client engagements may use official statistics, laws and regulator publications, company filings, product documentation, market databases, interviews and client-provided operating data. The best source depends on the decision and jurisdiction.",
      "Public pages on this site contain service descriptions and professional background. Previous employers are identified as experience, not as consulting clients, endorsements or current affiliations.",
    ],
    situations: [
      "Official sources are used for legal status, public policy and formal statistics where available.",
      "Primary company material is used for product and corporate claims, with independent checks where material.",
      "Time-sensitive facts record an observation or retrieval date in engagement outputs.",
      "Third-party estimates retain their original methodology and limitations.",
      "Confidential client evidence is not published without permission.",
    ],
    deliverables: [
      "Named source and direct link where publication is permitted",
      "Publication, observation and retrieval dates where relevant",
      "Geographic and definitional coverage",
      "Known gaps, conflicts and uncertainty",
      "Separate labels for fact, estimate and recommendation",
    ],
    process: "A source being published does not make it correct or suitable. Material claims are checked for authority, recency, definition, geography and incentives before use.",
    related: ["/methodology/", "/about/", "/industries/automotive/", "/industries/autonomous-mobility/"],
    faqs: [
      ["Does this site claim official authority?", "No. Žilić Consult is an independent consultancy and does not represent a government, regulator, previous employer or other official body."],
      ["Can confidential sources be cited publicly?", "Usually not. Engagement outputs identify confidential or client-provided evidence without exposing restricted material."],
    ],
  },
  {
    path: "/privacy/",
    family: "legal",
    title: "Privacy Notice | Žilić Consult",
    description: "Privacy notice for the Žilić Consult website, covering consent-based Google Analytics, email contact, hosting logs and requests about personal information.",
    eyebrow: "Privacy",
    h1: "Privacy notice.",
    answer: "This website uses no contact form and no advertising cookies. Google Analytics measurement runs only after you accept analytics cookies, and email you send is used to respond and manage the conversation.",
    intro: [
      "Email is handled by the email providers of the sender and recipient. Do not send confidential or sensitive information before appropriate engagement and confidentiality terms are agreed.",
      "The website is hosted by Vercel, which may process standard request and security logs under its own terms. Links to LinkedIn and other external sites are governed by those services.",
      "Google Analytics 4 is loaded with Google Consent Mode and analytics storage denied by default. No analytics cookie is written and no measurement event is stored until you choose Accept in the consent banner. Choosing Decline leaves the site working normally without analytics cookies, and IP addresses are truncated before processing.",
    ],
    situations: [
      "Information you choose to include in an email",
      "Normal technical request data processed by the hosting provider",
      "Aggregated page and traffic-source measurement in Google Analytics, only after you accept",
      "No advertising profile, remarketing audience or on-site account",
      "No sale of personal information",
    ],
    deliverables: [
      "You may request access, correction or deletion of email correspondence, subject to legal and contractual retention duties.",
      "You can change or withdraw an analytics choice at any time through the Cookie settings control in the site footer.",
      "Requests can be sent to tonci.zilic18@gmail.com.",
      "This notice may change if the website begins using additional services.",
    ],
    process: "Last materially reviewed on 21 August 2026. This notice is general information and is not a substitute for jurisdiction-specific legal advice.",
    related: ["/legal/", "/about/", "/"],
    faqs: [],
  },
  {
    path: "/legal/",
    family: "legal",
    title: "Website Terms & Legal Notice | Žilić Consult",
    description: "Legal notice for the Žilić Consult website covering general information, professional background, third-party links and engagement terms.",
    eyebrow: "Legal",
    h1: "Website terms and legal notice.",
    answer: "Content on this website is general information about independent consulting services. It is not legal, financial, investment, safety or regulatory advice.",
    intro: [
      "No consulting relationship is created by visiting the site or sending an initial message. Services, deliverables, fees, confidentiality, intellectual property and liability are governed only by a signed engagement agreement.",
      "References to previous employers describe professional background. They do not imply endorsement, affiliation or that those organizations are consulting clients.",
    ],
    situations: [
      "Information may become outdated despite reasonable care.",
      "External links are provided for context and remain third-party content.",
      "Regulated conclusions require qualified specialists and relevant authorities.",
      "No outcome, ranking, investment or commercial result is guaranteed.",
    ],
    deliverables: [
      "Site content may not be republished as an endorsement without permission.",
      "Brand names belong to their respective owners.",
      "Questions can be sent to tonci.zilic18@gmail.com.",
    ],
    process: "Last materially reviewed on 21 August 2026. Applicable contracting details are supplied before an engagement is formed.",
    related: ["/privacy/", "/methodology/", "/"],
    faqs: [],
  },
];

const hubs = [
  {
    path: "/services/",
    family: "hub",
    title: "Product, Market & Growth Consulting Services | Žilić Consult",
    description: "Focused consulting across product strategy, market readiness, market entry, B2B pricing, fundraising, advisory and interim leadership.",
    eyebrow: "Expertise",
    h1: "Focused engagements for product, market, funding and growth decisions.",
    answer: "Choose the decision or delivery gap in front of your team. Each engagement is direct, tightly scoped and designed to produce an executable output.",
    children: servicePages.map(({ path, h1, answer }) => ({ path, title: h1, summary: answer })),
  },
  {
    path: "/for/",
    family: "hub",
    title: "Advisory for CEOs, COOs, Product Leaders & Founders",
    description: "Direct independent advisory for B2B CEOs, COOs, product leaders and founders making product, market, pricing, launch and funding decisions.",
    eyebrow: "Who I work with",
    h1: "Direct support for leaders accountable for the decision.",
    answer: "Engagements are shaped around the leader, decision rights and team context—not a generic package with a title swapped into the copy.",
    children: audiencePages.map(({ path, h1, answer }) => ({ path, title: h1, summary: answer })),
  },
  {
    path: "/industries/",
    family: "hub",
    title: "Automotive, Mobility & B2B Technology Consulting",
    description: "Sector experience across automotive products, autonomous mobility, robotaxi services and complex B2B technology businesses.",
    eyebrow: "Industries",
    h1: "Sector depth where product and operations meet.",
    answer: "Žilić Consult focuses on sectors where technology, physical systems, commercial models and service operations must be designed together.",
    children: industryPages.map(({ path, h1, answer }) => ({ path, title: h1, summary: answer })),
  },
];

export const pages = [...hubs, ...servicePages, ...audiencePages, ...industryPages, ...institutionalPages].map((page) => ({
  lastModified: site.lastModified,
  ...page,
}));

export const pageByPath = new Map(pages.map((page) => [page.path, page]));

export const nav = [
  ["/services/", "Expertise"],
  ["/#engagements", "Engagements"],
  ["/about/", "About"],
  ["/how-i-work/", "How I work"],
];
